---
- name: sudoers
  become: true
  with_dict: sudoers
  blockinfile:
    dest: /etc/sudoers
    validate: '/usr/sbin/visudo -cf %s'
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ item.key }}"
    content: |
      {% for entry in item.value %}
      {{ entry }} ALL=(ALL) NOPASSWD:ALL
      {% endfor %}
